version: "3.8"
services:
  redis:
    container_name: redis-GAAS
    image: redis:7.0.11-alpine
    ports:
      - "6379:6379"
  django:
    container_name: django-GAAS
    build:
      context: .
      dockerfile: docker/python/DevDockerfile
    # command: sh -c "python manage.py migrate
    #                 && python manage.py runserver 0.0.0.0:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgresDB_origin
  celery_worker:
    container_name: celery_worker-GAAS
    build:
      context: .
      dockerfile: docker/python/DevDockerfile
    volumes:
      - ./backend/:/app/
    command: celery --app=core worker -l INFO -B -E -Q queue1,queue2,queue3 --schedule ./celerybeat-schedule

    env_file:
      - .env
    depends_on:
      - django
      - redis
  postgresDB_origin:
    image: postgres:16-alpine
    container_name: postgresDB_origin-GAAS
    hostname: localhost
    environment:
      POSTGRES_DB: ${ORIGIN_DB_NAME}
      POSTGRES_USER: ${ORIGIN_DB_USER}
      POSTGRES_PASSWORD: ${ORIGIN_DB_PASSWORD}
    ports:
      - ${ORIGIN_DB_PORT}:5432
    volumes:
      - postgres-origin-data:/var/lib/postgresql/data

volumes:
  postgres-origin-data:
  node_module:
